countries = {1: "spain", 2: "england", 3: "germany", 4: "italy", 5: "france", 6: "special"}

leagues = {
    "spain": {
        "name": "La Liga Santander",
        "teams": [
            "Real Madrid",
            "FC Barcelona",
            "Athletic Club",
            "Atlético Madrid",
            "Mallorca",
            "Villarreal",
            "Osasuna",
            "Deportivo Alavés",
            "Celta de Vigo",
            "Rayo Vallecano",
            "Real Betis",
            "Girona",
            "Sevilla",
            "Espanyol",
            "Leganés",
            "Real Sociedad",
            "Valencia",
            "Real Valladolid",
            "Getafe",
            "Las Palmas",
        ],
    },
    "england": {
        "name": "English Premier League",
        "teams": [
                "Arsenal",
                "Aston Villa",
                "AFC Bournemouth",
                "Brentford",
                "Brighton & Hove Albion",
                "Chelsea",
                "Crystal Palace",
                "Everton",
                "Fulham",
                "Ipswich Town",
                "Leicester City",
                "Liverpool",
                "Manchester City",
                "Manchester United",
                "Newcastle United",
                "Nottingham Forest",
                "Southampton",
                "Tottenham Hotspur",
                "West Ham United",
                "Wolverhampton Wanderers",
        ],
    },
    "germany": {
        "name": "Bundesliga",
        "teams": [
            "FC Bayern München",
            "Bayer 04 Leverkusen",
            "SC Freiburg",
            "Eintracht Frankfurt",
            "RB Leipzig",
            "FC Union Berlin",
            "VfB Stuttgart",
            "Borussia Dortmund",
            "Heidenheim",
            "FSV Mainz 05",
            "Werder Bremen",
            "FC Augsburg",
            "VfL Wolfsburg",
            "Borussia Mönchengladbach",
            "TSG Hoffenheim",
            "VfL Bochum 1848",
            "St. Pauli",
            "Holstein Kiel",
        ],
    },
    "italy": {
        "name": "Seria A",
        "teams": [
            "Torino",
            "Napoli",
            "Udinese",
            "Juventus",
            "Empoli",
            "Inter",
            "Milan",
            "Lazio",
            "Roma",
            "Hellas Verona",
            "Fiorentina",
            "Atalanta",
            "Bologna",
            "Parma",
            "Como",
            "Genoa",
            "Lecce",
            "Venezia",
            "Monza",
            "Cagliari",
        ],
    },
    "france": {
        "name": "Ligue 1",
        "teams": [
            "Paris Saint Germain",
            "Olympique de Marseille",
            "Monaco",
            "Lens",
            "Nantes",
            "Stade de Reims",
            "Nice",
            "Rennes",
            "Lille",
            "Strasbourg",
            "Brest",
            "Le Havre",
            "Toulouse",
            "Olympique Lyonnais",
            "Montpellier",
            "Saint-Étienne",
            "Auxerre",
            "Angers SCO",
        ],
    },
    "special": {
        "name": "Icons, Legends, Wonderkids",
        "teams": [
            "Icon",
            "Legends",
            "Wonderkids",
            "Hero",
        ],
    }
}
