countries = {1: "england", 2: "spain", 3: "germany", 4: "italy", 5: "france", 6: "portugal", 7: "belgium",
             8: "usa", 9: "denmark", 10: "netherlands", 11: "argentina", 12: "england2", 13: "turkey",
             14: "austria", 15: "spain2", 16: "switzerland", 17: "poland", 18: "germany2", 19: "italy2",
             20: "korea", 21: "sweden", 22: "norway", 23: "saudi arabia", 24: "france2", 25: "scotland",
             26: "china", 27: "india", 28: "special"}

leagues = {
    "spain": {
        "name": "LaLiga",
        "teams": [
            "Real Madrid",
            "FC Barcelona",
            "Athletic Club",
            "Atlético Madrid",
            "Mallorca",
            "Villarreal",
            "Osasuna",
            "Deportivo Alavés",
            "Celta de Vigo",
            "Rayo Vallecano",
            "Real Betis",
            "Girona",
            "Sevilla",
            "Real Sociedad",
            "Valencia",
            "Getafe",
            "Las Palmas",
            "Almería",
            "Cádiz",
            "Granada",
        ],
    },
    "england": {
        "name": "English Premier League",
        "teams": [
                "Arsenal",
                "Aston Villa",
                "AFC Bournemouth",
                "Brentford",
                "Brighton & Hove Albion",
                "Chelsea",
                "Crystal Palace",
                "Everton",
                "Fulham",
                "Luton Town",
                "Leicester City",
                "Liverpool",
                "Manchester City",
                "Manchester United",
                "Newcastle United",
                "Nottingham Forest",
                "Burnley",
                "Tottenham Hotspur",
                "West Ham United",
                "Wolverhampton Wanderers",
        ],
    },
    "germany": {
        "name": "Bundesliga",
        "teams": [
            "FC Bayern München",
            "Bayer 04 Leverkusen",
            "SC Freiburg",
            "Eintracht Frankfurt",
            "RB Leipzig",
            "FC Union Berlin",
            "VfB Stuttgart",
            "Borussia Dortmund",
            "Heidenheim",
            "FSV Mainz 05",
            "Werder Bremen",
            "FC Augsburg",
            "VfL Wolfsburg",
            "Borussia Mönchengladbach",
            "TSG Hoffenheim",
            "VfL Bochum 1848",
            "FC Köln",
            "Darmstadt 98",
        ],
    },
    "italy": {
        "name": "Seria A",
        "teams": [
            "Torino",
            "Napoli",
            "Udinese",
            "Juventus",
            "Empoli",
            "Inter",
            "Milan",
            "Lazio",
            "Roma",
            "Hellas Verona",
            "Fiorentina",
            "Atalanta",
            "Bologna",
            "Genoa",
            "Lecce",
            "Monza",
            "Cagliari",
            "Sassuolo",
            "Frosinone",
            "Salernitana",
        ],
    },
    "france": {
        "name": "Ligue 1",
        "teams": [
            "Paris Saint Germain",
            "Olympique de Marseille",
            "Monaco",
            "Lens",
            "Nantes",
            "Stade de Reims",
            "Nice",
            "Rennes",
            "Lille",
            "Strasbourg",
            "Brest",
            "Le Havre",
            "Toulouse",
            "Olympique Lyonnais",
            "Montpellier",
            "Metz",
            "Lorient",
            "Clermont",
        ],
    },
    "portugal": {
        "name": "Primeira Liga",
        "teams": [
            "Arouca",
            "Boavista",
            "Casa Pia",
            "Chaves",
            "Estrela Amadora",
            "Estoril",
            "Famalicão",
            "Farense",
            "Porto",
            "Gil Vicente",
            "Moreirense",
            "Portimonense",
            "Rio Ave",
            "Benfica",
            "Sporting CP",
            "Sporting Braga",
            "Vitória SC",
            "Vizela",
        ],
    },
    "belgium": {
        "name": "Jupiler Pro League",
        "teams": [
            "Cercle Brugge",
            "Sporting Charleroi",
            "Club Brugge",
            "AS Eupen",
            "Genk",
            "Gent",
            "Kortrijk",
            "OH Leuven",
            "Mechelen",
            "Antwerp",
            "RWDM",
            "Anderlecht",
            "Sint-Truiden",
            "Standard Liège",
            "Union Saint-Gilloise",
            "Westerlo",
        ],
    },
    "usa": {
        "name": "Major League Soccer",
        "teams": [
            "Atlanta United",
            "Austin",
            "CF Montréal",
            "Charlotte",
            "Chicago Fire",
            "Colorado Rapids",
            "Columbus Crew",
            "DC United",
            "Cincinnati",
            "Dallas",
            "Houston Dynamo",
            "Inter Miami",
            "LA Galaxy",
            "Los Angeles FC",
            "Minnesota United",
            "Nashville SC",
            "New England",
            "New York City",
            "New York RB",
            "Orlando City",
            "Philadelphia Union",
            "Portland Timbers",
            "Real Salt Lake",
            "San Jose Earthquakes",
            "Seattle Sounders",
            "Sporting Kansas City",
            "Saint Louis City",
            "Toronto",
        ],
    },
    "denmark": {
        "name": "3F Superliga",
        "teams": [
            "AGF",
            "Brøndby",
            "København" ,
            "Lyngby",
            "Midtjylland",
            "Nordsjælland",
            "OB",
            "Randers",
            "Silkeborg",
            "Vejle",
            "Viborg",
        ],
    },
    "netherlands": {
        "name": "Eredeivisie",
        "teams": [
            "Ajax",
            "Almere City",
            "AZ Alkmaar",
            "Excelsior",
            "FC Utrecht",
            "FC Volendam",
            "Feyenoord",
            "Fortuna Sittard",
            "Go Ahead Eagles",
            "Heracles Almelo",
            "NEC",
            "PEC Zwolle",
            "PSV",
            "RKC Waalwijk",
            "SC Heerenveen",
            "Sparta Rotterdam",
            "FC Twente",
            "Vitesse",
        ],
    },
    "argentina": {
        "name": "Liga Profesional",
        "teams": [
            "Argentinos Juniors",
            "Arsenal de Sarandi",
            "Atlético Tucumán",
            "Barracas Central",
            "Banfield",
            "Belgrano",
            "Boca Juniors",
            "Central Cordoba SdE",
            "Colón",
            "Defensa y Justicia",
            "Estudiantes",
            "Gimnasia La Plata",
            "Godoy Cruz",
            "Huracán",
            "Independiente del Valle",
            "Instituto",
            "Lanús",
            "Newell's Old Boys",
            "Platense",
            "Racing Club",
            "River Plate",
            "Rosario Central",
            "San Lorenzo",
            "Sarmiento",
            "Talleres Córdoba",
            "Tigre",
            "Unión Santa Fe",
            "Vélez Sarsfield",
        ],
    },
    "england2": {
        "name": "EFL Championship",
        "teams": [
            "Birmingham City",
            "Blackburn Rovers",
            "Bristol City",
            "Cardiff City",
            "Coventry City",
            "Huddersfield Town",
            "Hull City",
            "Leeds United",
            "Leicester City",
            "Ipswich Town",
            "Middlesbrough",
            "Millwall",
            "Norwich City",
            "Plymouth Argyle",
            "Preston North End",
            "Queens Park Rangers",
            "Rotherham United",
            "Sheffield Wednesday",
            "Southampton",
            "Stoke City",
            "Sunderland",
            "Swansea City",
            "Watford",
            "West Bromwich Albion",
        ],
    },
    "turkey": {
        "name": "Süper Lig",
        "teams": [
            "Adana Demirspor",
            "Alanyaspor",
            "Ankaragücü",
            "Antalyaspor",
            "Beşiktaş",
            "Fatih Karagümrük",
            "Fenerbahçe",
            "Galatasaray",
            "Gaziantep F.K.",
            "Hatayspor",
            "İstanbul Başakşehir",
            "İstanbulspor",
            "Kasımpaşa",
            "Kayserispor",
            "Konyaspor",
            "Pendikspor",
            "Rizespor",
            "Samsunspor",
            "Sivasspor",
            "Trabzonspor",
        ],
    },
    "austria": {
        "name": "Admiral Bundesliga",
        "teams": [
            "Austria Klagenfurt",
            "Austria Lustenau",
            "Blau-Weiß Linz",
            "Salzburg",
            "Austria Wien",
            "LASK Linz",
            "Rheindorf Altach",
            "Rapid Wien",
            "Sturm Graz",
            "Hartberg",
            "Wolfsberger AC",
            "WSG Tirol",
        ],
    },
    "norway": {
        "name": "Eliteserien",
        "teams": [
            "Aalesund",
            "Bodø / Glimt",
            "Brann", "HamKam",
            "Haugesund",
            "Lillestrøm",
            "Molde",
            "Odd",
            "Rosenborg",
            "Sandefjord",
            "Sarpsborg 08",
            "Stabæk",
            "Strømsgodset",
            "Tromsø",
            "Vålerenga",
            "Viking",
        ],
    },
    "india": {
        "name": "Indian Super League",
        "teams": [
            "ATK Mohun Bagan",
            "Bengaluru",
            "Chennaiyin",
            "East Bengal",
            "Goa",
            "Hyderabad",
            "Jamshedpur",
            "Kerala Blasters",
            "Mumbai City",
            "NorthEast United",
            "Odisha FC",
            "Punjab",
        ],
    },
    "spain2": {
        "name": "LaLiga 2",
        "teams": [
            "Albacete",
            "Alcorcón",
            "Amorebieta",
            "FC Andorra",
            "Burgos",
            "FC Cartagena",
            "SD Eibar",
            "Elche",
            "Eldense",
            "Espanyol",
            "Huesca",
            "Leganés",
            "Levante",
            "Mirandés",
            "Racing Santander",
            "Racing Ferrol",
            "Real Oviedo",
            "Sporting Gijón",
            "Tenerife",
            "Real Valladolid",
            "Villarreal B",
            "Real Zaragoza",
        ],
    },
    "switzerland": {
        "name": "Swiss Super League",
        "teams": [
            "Young Boys",
            "Basel",
            "Lausanne Sport",
            "Lugano",
            "Luzern",
            "St. Gallen",
            "Zürich",
            "Grasshopper",
            "Stade Lausanne-Ouchy",
            "Servette",
            "Winterthur",
            "Yverdon Sport",
        ],
    },
    "poland": {
        "name": "Ekstraklasa",
        "teams": [
            "Cracovia Kraków",
            "Górnik Zabrze",
            "Jagiellonia Białystok",
            "Korona Kielce",
            "Lech Poznań",
            "Legia Warszawa",
            "ŁKS Łódź",
            "Stal Mielec",
            "Piast Gliwice",
            "Pogoń Szczecin",
            "Puszcza Niepołomice",
            "Radomiak Radom",
            "Raków Częstochowa",
            "Ruch Chorzów",
            "Śląsk Wrocław",
            "Warta Poznań",
            "Widzew Łódź",
            "Zagłębie Lubin",
        ],
    },
    "saudi arabia": {
        "name": "Saudi Pro League",
        "teams": [
            "Abha",
            "Al Ahli Jeddah",
            "Al Fateh",
            "Al Fayha",
            "Al Hazem",
            "Al Hilal",
            "Al Ittihad",
            "Al Khaleej",
            "Al Nassr",
            "Al Okhdood",
            "Al Raed",
            "Al Riyadh",
            "Al Shabab",
            "Al Tai",
            "Damac",
            "Al Ettifaq",
            "Al Taawoun",
            "Al Wahda",
        ],
    },
    "germany2": {
        "name": "2. Bundesliga",
        "teams": [
            "Kaiserslautern",
            "Magdeburg",
            "Nürnberg",
            "Eintracht Braunschweig",
            "Elversberg",
            "St. Pauli",
            "Fortuna Düsseldorf",
            "SpVgg Greuther Fürth",
            "Hamburger SV",
            "Hannover 96",
            "Hansa Rostock",
            "Hertha BSC",
            "Holstein Kiel",
            "Karlsruher SC",
            "Paderborn",
            "Schalke 04",
            "Osnabrück",
            "Wehen Wiesbaden",
        ],
    },
    "italy2": {
        "name": "Serie B",
        "teams": [
            "Ascoli",
            "Bari 1908",
            "Catanzaro",
            "Cittadella",
            "Como",
            "Cosenza",
            "Cremonese",
            "Feralpisalò",
            "Lecco",
            "Modena",
            "Palermo",
            "Parma",
            "Pisa",
            "Reggiana",
            "Sampdoria",
            "Spezia",
            "Südtirol",
            "Ternana",
            "Venezia",
        ],
    },
    "korea": {
        "name": "K-League 1",
        "teams" : [
            "Daegu",
            "Daejeon Citizen",
            "Seoul",
            "Gangwon",
            "Gwangju",
            "Incheon United",
            "Jeonbuk Motors",
            "Jeju United",
            "Pohang Steelers",
            "Suwon",
            "Suwon Bluewings",
            "Ulsan",
        ],
    },
    "sweden": {
        "name": "Allsvenskan",
        "teams" : [
            "AIK",
            "Häcken",
            "Degerfors",
            "Djurgården",
            "Halmstad",
            "Hammarby",
            "Brommapojkarna",
            "Elfsborg",
            "IFK Göteborg",
            "Norrköping",
            "Värnamo",
            "Sirius",
            "Kalmar",
            "Malmö FF",
            "Mjällby",
            "Varberg BoIS",
        ],
    },
    "france2": {
        "name": "Ligue 2",
        "teams": [
            "Ajaccio",
            "Amiens SC",
            "Angers SCO",
            "Auxerre",
            "Saint-Étienne",
            "Concarneau",
            "Dunkerque",
            "Guingamp",
            "Bordeaux",
            "Grenoble Foot 38",
            "Laval",
            "Paris",
            "Pau",
            "Rodez",
            "Bastia",
            "Caen",
            "Quevilly Rouen",
            "Troyes",
            "Valenciennes",
        ],
    },
    "scotland": {
        "name": "cinch Premiership",
        "teams": [
            "Aberdeen",
            "Celtic",
            "Dundee",
            "Hearts",
            "Hibernian",
            "Kilmarnock",
            "Livingston",
            "Motherwell",
            "Rangers",
            "Ross County",
            "St. Johnstone",
            "St. Mirren",
        ],
    },
    "china": {
        "name": "Chinese Super League",
        "teams": [
            "Beijing Guoan",
            "Cangzhou Mighty Lions",
            "Changchun Yatai",
            "Chengdu Rongcheng",
            "Dalian Professional",
            "Henan",
            "Meizhou Hakka",
            "Nantong Zhiyun",
            "Qingdao Hainiu",
            "Shandong Taishan",
            "Shanghai Shenhua",
            "Shanghai Port",
            "Shenzhen",
            "Tianjin Jinmen Tiger",
            "Wuhan Three Towns",
            "Zhejiang",
        ],
    },
    "special": {
        "name": "Icons, Legends, Wonderkids",
        "teams": [
            "Icon",
            "Legends",
            "Wonderkids",
            "Hero",
        ],
    }
}
